# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 2.1.302

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_5f2f0abc34db_key -iv $encrypted_5f2f0abc34db_iv -in travis-appsettings.config.enc -out travis-appsettings.config -d
  - mv -f travis-appsettings.config src/CloudFileStore.Tests/appsettings.json

script:
  - dotnet restore
  - dotnet build -c Release  
  - pushd src/CloudFileStore.Tests
  - dotnet test
  - popd
  - dotnet pack -c Release /p:PackageVersion=1.0.$TRAVIS_BUILD_NUMBER
  - dotnet nuget push "src/CloudFileStore/bin/Release/CloudFileStore.1.0.$TRAVIS_BUILD_NUMBER.nupkg" --api-key "$NUGET_KEY" --source https://api.nuget.org/v3/index.json