language: csharp
dotnet: 3.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_f84939ba13f7_key -iv $encrypted_f84939ba13f7_iv
  -in travis-appsettings.config.enc -out travis-appsettings.config -d
- mv -f travis-appsettings.config src/CloudFileStore.Tests/appsettings.json
script:
- dotnet restore
- dotnet build -c Release
- pushd src/CloudFileStore.Tests
- dotnet test -v detailed --logger:"console;noprogress=true"
- popd
- dotnet pack -c Release /p:PackageVersion=1.0.$TRAVIS_BUILD_NUMBER
- dotnet nuget push "src/CloudFileStore/bin/Release/CloudFileStore.1.0.$TRAVIS_BUILD_NUMBER.nupkg"
  --api-key "$NUGET_KEY" --source https://api.nuget.org/v3/index.json
