steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=googlecloud.appsettings.json.enc
      - --plaintext-file=glcoud-appsettings.json
      - --location=global
      - --keyring=github-builds
      - --key=default-key

  - name: bash
    args: ['mv',  '-f', 'glcoud-appsettings.json', './src/CloudFileStore.Tests/appsettings.json']

  - name: mcr.microsoft.com/dotnet/core/sdk:3.0
    entrypoint: dotnet
    args: ['build']
    
  - name: mcr.microsoft.com/dotnet/core/sdk:3.0
    entrypoint: dotnet
    args: ['test src/CloudFileStore.Tests']  
