steps:
- name: mcr.microsoft.com/dotnet/core/sdk:3.0
  entrypoint: dotnet
  args: ['build']
  
- name: mcr.microsoft.com/dotnet/core/sdk:3.0
  entrypoint: dotnet
  args: ['test src/CloudFileStore.Tests']  
