name: .NET build, publish and nuget push

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: "9.0"
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  integration-tests:
    needs: build
    uses: ./.github/workflows/integration-tests.yml
    with:
      dotnet-version: '9.0.x'
    secrets:
      GOOGLE_AUTH_JSON: ${{ secrets.GOOGLE_AUTH_JSON }}

  publish:
    needs: integration-tests
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: "9.0"
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for release
      run: dotnet build --no-restore -c Release

    - name: Publish the package to Nuget
      if: github.event_name != 'pull_request' && github.actor == github.repository_owner
      run: |
        export PACKAGE_VERSION="$VERSION_NUMBER.$GITHUB_RUN_NUMBER"
        dotnet pack -c Release /p:PackageVersion=$PACKAGE_VERSION
        dotnet nuget push src/CloudFileStore/bin/Release/CloudFileStore.$PACKAGE_VERSION.nupkg --api-key "$NUGET_KEY" --source https://api.nuget.org/v3/index.json 
