# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name Write appsettings for tests
      run: |
        sed "s|//GOOGLE_CONFIGURATION|${{ secrets.GOOGLE_CONFIGURATION }}|" src/CloudFileStore.Tests/appsettings.gha-template.json > src/CloudFileStore.Tests/appsettings.temp.json
        sed -i "s|{AWS_BUCKETNAME}|${{ secrets.AWS_BUCKETNAME }}|" src/CloudFileStore.Tests/appsettings.temp.json
        sed -i "s|{AWS_SECRETKEY}|${{ secrets.AWS_SECRETKEY }}|" src/CloudFileStore.Tests/appsettings.temp.json
        sed -i "s|{AWS_ACCESSKEY}|${{ secrets.AWS_ACCESSKEY }}|" src/CloudFileStore.Tests/appsettings.temp.json
        sed -i "s|{AZURE_CONTAINERNAME}|${{ secrets.AZURE_CONTAINERNAME }}|" src/CloudFileStore.Tests/appsettings.temp.json
        sed -i "s|{AZURE_CONNECTIONSTRING}|${{ secrets.AZURE_CONNECTIONSTRING }}|" src/CloudFileStore.Tests/appsettings.temp.json
        mv src/CloudFileStore.Tests/appsettings.temp.json src/CloudFileStore.Tests/appsettings.json
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Create the package
      run: dotnet pack --configuration Release /p:PackageVersion=8.0.${{ github.run_number }}

    - name: Publish the package to Nuget
      if: github.event_name != 'pull_request' && github.actor == github.repository_owner
      run: dotnet nuget push src/CloudFileStore/bin/Release/8.0.${{ github.run_number }}.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json 